export const listData1 = [
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekendssss?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'Tinggi',
    status: 'Read',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 2,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'Rendah',
    status: 'Sekretaris',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 3,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'Rendah',
    status: 'Disposisi',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 4,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'Tinggi',
    status: 'Disposisi',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 5,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'Tinggi',
    status: 'Unread',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 6,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'Sedang',
    status: 'Read',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 7,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'Sedang',
    status: 'Read',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 8,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'Sedang',
    status: 'Unread',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 9,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'Tinggi',
    status: 'Read',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
];
export const listData2 = [
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'Rendah',
    status: 'Sekretaris',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 2,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'Rendah',
    status: 'Sekretaris',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 3,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'Sedang',
    status: 'Disposisi',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 4,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'Sedang',
    status: 'Disposisi',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'Tinggi',
    status: 'Unread',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'Tinggi',
    status: 'Read',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
];
export const listData3 = [
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '10:30, 22 Sep',
    priority: 'Tinggi',
    status: 'Read',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 2,
    date: '09:00, 23 Sep',
    priority: 'Rendah',
    status: 'Unread',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
  {
    id: 1,
    avatarSrc: '/static/images/avatar/1.jpg',
    primary: 'Brunch this weekend?',
    secondary: "Ali Connors — I'll be in your neighborhood doing errands this…",
    messageCount: 14,
    date: '15:45, 24 Sep',
    priority: 'Sedang',
    status: 'Unread',
    file: [
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
      { name: 'Preview Surat.pdf', size: 12345691 },
    ],
  },
];
