import user from '../../../../assets/vector/Avatar.png';

export const data = [
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'atasan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
  {
    profil: user,
    jabatan: 'bawahan',
    nama: 'lala',
    pgs: 'pgs',
    nik: '2121212',
    departemen: 'Departemen',
  },
];
